### PR TITLE
Add the Signalen and OpenZaak logos to the index

### PR DESCRIPTION
**Pull request by bvhme**
On the suggestion of @clausmullie 

image

### CODE REVIEW

**Comment by ElenaFdR** [comment]
What's the purpose of this change? Which user groups have asked for this? 

The other user needs for the homepage I'm already aware of: 

- #120 expressed as #122
- @nebster says /background is the most important link on the homepage for the folks he talks to
- #106 is apparently the first question in all early membership conversations

**Comment by ElenaFdR** [comment]
Separate from its purpose, there's a weird relationship between the placement of the 2 codebase links and the sentence above, "We're proud to work with these codebase communities." It would make more sense to me if the 2 codebases were more clearly visually nested under that sentence. Could they be H3s, instead of H2s?

**Comment by ElenaFdR** [comment]
@angelplasma, can you consider this for the homepage redesign? I'll defer to your view as our design expert.

**Comment by angelplasma** [comment]
There are generally two kinds of value from such a 'logo wall':

1. A halo effect from the partners, which benefits the page owner
2. A statement of pride from the page owner, meant to lift up the partners (and potentially encourage new partners)

I suspect this idea would not be successful (yet) on the first count (see rationale below), but I think a stronger case can be made for the second case—the Foundation visibly lifting up its partners.

**So then: What is the desired effect of including these logos on the homepage?**

**Further rationale on #1:**
 - Logo walls (or carousels, etc) have positive impact when they contain easily recognizable entities, whose known reputations then confer a halo effect on the page owner.
 - If a wall contains too few or leads with relatively unknown entities, the halo effect is often reversed, and vaguely negative.
 - The equation is thus: are there enough people already familiar with and of strongly favorable opinions of the orgs in question to justify the wall's existence.
 - In this case, I suspect (and Elena tends to concur) that the orgs in question are—though representing important partnerships of which to be proud—not well-known enough to have the positive impact we'd want, in order to justify adding complexity to the main page.

**Comment by clausmullie** [comment]
Closing this pull request based on @angelplasma's valid reasoning.

**Pull request closed without merging**
