### PR TITLE
updated bio

### PR DESCRIPTION
**Pull request by demkodo**
Updated my bio

-----
[View rendered team/deborah-meibergen.md](https://github.com/publiccodenet/publiccode.net/blob/update-bio-deborah/team/deborah-meibergen.md)

### CODE REVIEW

**Review by ElenaFdR — APPROVED** [review]
Great changes!

**Comment by demkodo** [comment]
wow, the error Travis is throwing at us (999 no error) seems to be a thing for years already: 
https://github.com/gjtorikian/html-proofer/issues/215
I don't know how I can resolve it. I do still want to link to my LinkedIn :) 
Help!!!

**Comment by bvhme** [comment]
Hey Deborah, we don't link to LinkedIn profiles since the content cannot be viewed without agreeing to their terms of service, this is hostile towards the user since it forces them to give up their rights to view the content and thus it would not be moral for us to link to that. If there is another place where that content is available like a personal site you can link that.

**Comment by demkodo** [comment]
> Hey Deborah, we don't link to LinkedIn profiles since the content cannot be viewed without agreeing to their terms of service, this is hostile towards the user since it forces them to give up their rights to view the content and thus it would not be moral for us to link to that. If there is another place where that content is available like a personal site you can link that.

Ah that's a valid point! I'll add the link to my website instead :) thanks!!

**Review by Ainali — APPROVED** [review]

**Review by bvhme — APPROVED** [review]

**Pull request merged**
